
import { mkdirSync } from 'fs';
import { join } from 'path';

const baseDir = 'C:/Users/dm/Documents/dm-langgraphjs/Docs';

const dirsToCreate = [
    'tutorials/quickstart',
    'tutorials/workflows',
    'tutorials/langgraph-platform/local-server',
    'cloud/quick_start',
    'concepts/high_level',
    'concepts/low_level',
    'concepts/agentic_concepts',
    'concepts/multi_agent',
    'concepts/breakpoints',
    'concepts/human_in_the_loop',
    'concepts/time-travel',
    'concepts/persistence',
    'concepts/memory',
    'concepts/streaming',
    'concepts/functional_api',
    'concepts/faq',
    'how-tos/map-reduce',
    'how-tos/command',
    'how-tos/defer-node-execution',
    'how-tos/configuration',
    'how-tos/persistence',
    'how-tos/subgraph-persistence',
    'how-tos/cross-thread-persistence',
    'how-tos/persistence-functional',
    'how-tos/cross-thread-persistence-functional',
    'how-tos/human_in_the_loop/wait-user-input',
    'how-tos/human_in_the_loop/review-tool-calls',
    'how-tos/human_in_the_loop/breakpoints',
    'how-tos/human_in_the_loop/edit-graph-state',
    'how-tos/wait-user-input-functional',
    'how-tos/review-tool-calls-functional',
    'how-tos/time-travel',
    'how-tos/stream-values',
    'how-tos/stream-updates',
    'how-tos/stream-tokens',
    'how-tos/streaming-tokens-without-langchain',
    'how-tos/streaming-content',
    'how-tos/stream-multiple',
    'how-tos/streaming-events-from-within-tools',
    'how-tos/streaming-from-final-node',
    'how-tos/tool-calling',
    'how-tos/force-calling-a-tool-first',
    'how-tos/tool-calling-errors',
    'how-tos/pass-run-time-values-to-tools',
    'how-tos/update-state-from-tools',
    'how-tos/subgraph',
    'how-tos/subgraphs-manage-state',
    'how-tos/subgraph-transform-state',
    'how-tos/multi-agent-network',
    'how-tos/multi-agent-multi-turn-convo',
    'how-tos/multi-agent-network-functional',
    'how-tos/multi-agent-multi-turn-convo-functional',
    'how-tos/define-state',
    'how-tos/input_output_schema',
    'how-tos/pass_private_state',
    'how-tos/node-retry-policies',
    'how-tos/node-caching',
    'how-tos/dynamically-returning-directly',
    'how-tos/respond-in-format',
    'how-tos/managing-agent-steps',
    'how-tos/create-react-agent',
    'how-tos/react-memory',
    'how-tos/react-system-prompt',
    'how-tos/react-human-in_the_loop',
    'how-tos/react-return-structured-output',
    'how-tos/react-agent-from-scratch-functional',
    'cloud/deployment/setup',
    'cloud/deployment/setup_pyproject',
    'cloud/deployment/setup_javascript',
    'cloud/deployment/custom_docker',
    'cloud/deployment/test_locally',
    'cloud/how-tos/use_stream_react',
    'cloud/deployment/cloud',
    'how-tos/deploy-self-hosted',
    'how-tos/use-remote-graph',
    'concepts/assistants',
    'cloud/how-tos/configuration_cloud',
    'cloud/how-tos/assistant_versioning',
    'cloud/how-tos/copy_threads',
    'cloud/how-tos/check_thread_status',
    'cloud/how-tos/background_run',
    'cloud/how-tos/same-thread',
    'cloud/how-tos/cron_jobs',
    'cloud/how-tos/stateless_runs',
    'cloud/how-tos/stream_values',
    'cloud/how-tos/stream_updates',
    'cloud/how-tos/stream_messages',
    'cloud/how-tos/stream_events',
    'cloud/how-tos/stream_debug',
    'cloud/how-tos/stream_multiple',
    'cloud/how-tos/generative_ui_react',
    'cloud/how-tos/human_in_the_loop_breakpoint',
    'cloud/how-tos/human_in_the_loop_user_input',
    'cloud/how-tos/human_in_the_loop_edit_state',
    'cloud/how-tos/human_in_the_loop_time_travel',
    'cloud/how-tos/human_in_the_loop_review_tool_calls',
    'cloud/how-tos/interrupt_concurrent',
    'cloud/how-tos/rollback_concurrent',
    'cloud/how-tos/reject_concurrent',
    'cloud/how-tos/enqueue_concurrent',
    'cloud/how-tos/webhooks',
    'cloud/how-tos/cron_jobs',
    'cloud/how-tos/test_deployment',
    'cloud/how-tos/test_local_deployment',
    'cloud/how-tos/invoke_studio',
    'cloud/how-tos/threads_studio',
    'troubleshooting/errors/GRAPH_RECURSION_LIMIT',
    'troubleshooting/errors/INVALID_CONCURRENT_GRAPH_UPDATE',
    'troubleshooting/errors/INVALID_GRAPH_NODE_RETURN_VALUE',
    'troubleshooting/errors/MULTIPLE_SUBGRAPHS',
    'troubleshooting/errors/UNREACHABLE_NODE'
];

dirsToCreate.forEach(dir => {
    const fullPath = join(baseDir, dir);
    try {
        mkdirSync(fullPath, { recursive: true });
        console.log(`Created directory: ${fullPath}`);
    } catch (error) {
        console.error(`Error creating directory ${fullPath}: ${error}`);
    }
});
